# Generated by Django 5.0.14 on 2026-07-20 07:42

import core.models
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Направление',
                'verbose_name_plural': 'Направления',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=220, unique=True, verbose_name='Адрес (slug)')),
                ('type', models.CharField(choices=[('lesson', 'Конспект'), ('practice', 'Разработка'), ('video', 'Видео'), ('interactive', 'Интерактив'), ('article', 'Статья')], default='lesson', max_length=20, verbose_name='Тип')),
                ('excerpt', models.CharField(help_text='Показывается в карточке материала', max_length=300, verbose_name='Краткое описание')),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Содержание')),
                ('video_url', models.URLField(blank=True, help_text='YouTube, RuTube или VK Видео — будет встроен плеер', verbose_name='Ссылка на видео')),
                ('embed_code', models.TextField(blank=True, help_text='iframe PhET, GeoGebra и т.п. Только для типа «Интерактив»', verbose_name='Код встраивания (интерактив)')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Материал',
                'verbose_name_plural': 'Материалы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('url', models.URLField(verbose_name='Адрес')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Ссылка',
                'verbose_name_plural': 'Ссылки',
            },
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.models.attachment_path, verbose_name='Файл')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='Название для отображения')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='core.material', verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Вложение',
                'verbose_name_plural': 'Вложения',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Адрес (slug)')),
                ('icon', models.CharField(default='📚', max_length=10, verbose_name='Иконка (эмодзи)')),
                ('color', models.CharField(default='#2563EB', max_length=7, verbose_name='Цвет (hex)')),
                ('description', models.CharField(blank=True, max_length=250, verbose_name='Короткое описание')),
                ('is_hidden', models.BooleanField(default=False, help_text='Не показывается на главной, в меню и поиске. Доступен только по прямой ссылке. Для частных занятий.', verbose_name='Скрытый предмет')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subjects', to='core.direction', verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='core.subject', verbose_name='Предмет'),
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=50, verbose_name='Отчество')),
                ('last_name', models.CharField(max_length=50, verbose_name='Фамилия')),
                ('show_last_name', models.BooleanField(default=True, help_text='Если выключено, на сайте будет «Имя Отчество Ф.»', verbose_name='Показывать фамилию на сайте')),
                ('code', models.SlugField(help_text='Латиница, коротко. Адрес: /t/код/', unique=True, verbose_name='Код страницы')),
                ('role', models.CharField(blank=True, help_text='Например: учитель физики и информатики', max_length=150, verbose_name='Должность')),
                ('bio', models.TextField(blank=True, verbose_name='О себе')),
                ('color', models.CharField(default='#4F46E5', max_length=7, verbose_name='Цвет аватара (hex)')),
                ('brand_symbol', models.CharField(blank=True, help_text='Например: ∑. Если пусто — будут инициалы', max_length=10, verbose_name='Символ логотипа кабинета')),
                ('brand_title', models.CharField(blank=True, help_text='Например: Физика и код. Если пусто — отображаемое имя', max_length=100, verbose_name='Название кабинета')),
                ('subjects', models.ManyToManyField(blank=True, related_name='teachers', to='core.subject', verbose_name='Предметы')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profile', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Преподаватель',
                'verbose_name_plural': 'Преподаватели',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.AddField(
            model_name='material',
            name='author',
            field=models.ForeignKey(help_text='Заполняется автоматически', on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='core.teacherprofile', verbose_name='Автор'),
        ),
    ]
