# Generated by Django 5.0.14 on 2026-07-20 11:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=core.models.attachment_path, validators=[core.models.validate_file_size], verbose_name='Файл'),
        ),
    ]
