# Generated by Django 5.0.14 on 2026-07-20 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_attachment_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='material',
            options={'ordering': ['created_at'], 'verbose_name': 'Материал', 'verbose_name_plural': 'Материалы'},
        ),
        migrations.AddField(
            model_name='subject',
            name='emoji',
            field=models.CharField(blank=True, choices=[('', '— без эмодзи —'), ('📐', '📐 Математика'), ('➗', '➗ Алгебра'), ('📏', '📏 Геометрия'), ('⚛️', '⚛️ Физика'), ('🧪', '🧪 Химия'), ('🧬', '🧬 Биология'), ('🌍', '🌍 География'), ('📜', '📜 История'), ('🏛️', '🏛️ Обществознание'), ('📖', '📖 Литература'), ('✏️', '✏️ Русский язык'), ('🇬🇧', '🇬🇧 Английский язык'), ('🇩🇪', '🇩🇪 Немецкий язык'), ('🇫🇷', '🇫🇷 Французский язык'), ('🇨🇳', '🇨🇳 Китайский язык'), ('💻', '💻 Информатика'), ('🎨', '🎨 Искусство/ИЗО'), ('🎵', '🎵 Музыка'), ('⚽', '⚽ Физкультура'), ('🔭', '🔭 Астрономия'), ('🤖', '🤖 Робототехника'), ('🧮', '🧮 Олимпиадная математика'), ('🐍', '🐍 Python'), ('☕', '☕ Java'), ('⚡', '⚡ C++'), ('🔷', '🔷 C#'), ('🌐', '🌐 JavaScript'), ('📜', '📜 TypeScript'), ('🐘', '🐘 PHP'), ('💎', '💎 Ruby'), ('🐹', '🐹 Go'), ('🦀', '🦀 Rust'), ('🍎', '🍎 Swift'), ('🤖', '🤖 Kotlin'), ('🎯', '🎯 Dart'), ('🗄️', '🗄️ SQL/Базы данных'), ('🖥️', '🖥️ Веб-разработка (HTML/CSS)'), ('📊', '📊 Анализ данных'), ('🧠', '🧠 Machine Learning'), ('🐧', '🐧 Linux/Администрирование'), ('🎮', '🎮 Разработка игр')], default='', help_text='Иконка предмета для меню и страниц', max_length=8, verbose_name='Эмодзи'),
        ),
    ]
