# Generated by Django 5.0.14 on 2026-07-20 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_material_options_subject_emoji'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='color',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='icon',
        ),
    ]
