# Generated by Django 5.0.14 on 2026-07-20 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_subject_color_remove_subject_icon'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='emoji',
            new_name='icon',
        ),
    ]
