# Generated by Django 5.0.14 on 2026-07-21 09:45

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_emoji_subject_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='simulation_file',
            field=models.FileField(blank=True, help_text='Своя модель (HTML+CSS+JS в одном .html файле). Встроится в страницу материала. Только для типа «Интерактив»', upload_to=core.models.simulation_path, validators=[core.models.validate_html_file], verbose_name='HTML-файл интерактивной модели'),
        ),
    ]
