# Generated by Django 5.0.14 on 2026-07-21 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_subject_options_subject_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherprofile',
            name='brand_headline',
            field=models.CharField(blank=True, help_text='Например: Материалы по [физике] и [программированию] — понятно и с практикой. Слова в [скобках] будут выделены цветом. Если пусто — отображаемое имя', max_length=200, verbose_name='Заголовок кабинета'),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='brand_tagline',
            field=models.TextField(blank=True, help_text='Например: Конспекты уроков, лабораторные работы, видеоразборы и интерактивные модели. Если пусто — будет bio', verbose_name='Подзаголовок кабинета'),
        ),
    ]
