# Generated by Django 5.0.14 on 2026-07-22 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_teacherprofile_brand_headline_and_more'),
    ]

    operations = [
    ]
