# Generated by Django 5.0.14 on 2026-07-25 21:17

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_add_validators'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_enabled', models.BooleanField(default=True, help_text='Снимите галочку — раздел исчезнет из кабинета, данные проверок сохранятся.', verbose_name='Методический анализ включён')),
            ],
            options={
                'verbose_name': 'Настройки портала',
                'verbose_name_plural': 'Настройки портала',
            },
        ),
        migrations.AlterField(
            model_name='attachment',
            name='file',
            field=models.FileField(upload_to=core.models.attachment_path, validators=[core.models.validate_file_size, core.models.validate_attachment_file], verbose_name='Файл'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название проверки')),
                ('level', models.CharField(choices=[('ooo', 'ФГОС ООО (5–9 классы)'), ('soo', 'ФГОС СОО (10–11 классы)'), ('spo', 'ФГОС СПО (колледж)')], max_length=10, verbose_name='Уровень')),
                ('input_text', models.TextField(verbose_name='Проверяемый текст')),
                ('text_hash', models.CharField(db_index=True, max_length=64, verbose_name='Хэш текста')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('done', 'Готов'), ('error', 'Ошибка')], default='pending', max_length=10, verbose_name='Статус')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка (0–10)')),
                ('result', models.JSONField(blank=True, null=True, verbose_name='Результат (JSON)')),
                ('error', models.CharField(blank=True, max_length=300, verbose_name='Текст ошибки')),
                ('from_cache', models.BooleanField(default=False, verbose_name='Из кэша')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.teacherprofile', verbose_name='Преподаватель')),
            ],
            options={
                'verbose_name': 'Методическая проверка',
                'verbose_name_plural': 'Методические проверки',
                'ordering': ['-created_at'],
            },
        ),
    ]
